name: github CI

on:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12.x'

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modeuls
          key: ${{ runner.os }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: yarn install --pure-lockfile

      - name: Lint
        run: yarn run lint

      - name: Test
        run: yarn run test:badges
